[package]
name = "automancy-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22"
env_logger = "0.10"
rfd = "0.11.4"
chrono = "0.4.26"